# Generated by Django 6.0.3 on 2026-03-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="Category",
            new_name="category",
        ),
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.IntegerField(default=120, help_text="Duration in minutes"),
        ),
        migrations.AddField(
            model_name="movie",
            name="year",
            field=models.IntegerField(default=2000),
        ),
    ]
