# Generated by Django 6.0.3 on 2026-03-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0002_rename_category_movie_category_movie_duration_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
